---
# tasks file for /home/ec2-user/ansible/roles/react
- name: copy files to the react node
  ansible.builtin.copy:
    src: /home/ec2-user/ansible-project/react/
    dest: /home/ec2-user/react

- name: remove tech_react container
  community.docker.docker_container:
    name: tech_react
    state: absent
    force_kill: true

- name: remove techpro/react image
  community.docker.docker_image:
    name: techpro/react
    state: absent

- name: build image
  community.docker.docker_image:
    name: techpro/react
    build:
      path: /home/ec2-user/react
    source: build
    state: present
  register: image_info

- name: print the image_info
  ansible.builtin.debug:
    var: image_info

- name: run tech_react container
  community.docker.docker_container:
    name: tech_react    
    image: techpro/react 
    state: started
    ports:
    - "3000:3000"
    
  register: container_info

- name: print the container_info
  ansible.builtin.debug:
    var: container_info
    
